events {}
# otherwise nginx will raise an error

http {
    include /etc/nginx/mime.types;
    # to prevent errors linked to CSS
    server {
        listen 443 ssl;
        ssl_protocols TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        root /var/www/wordpress;
        server_name apeuget.42.fr;

        index index.php

        location / {
            include snippets/fastcgi-php.conf;
            # to be able to use fastcgi I guess ?
            try_files $uri $uri/ =404;
        
        location ~ \.php$ {
            fastcgi_pass wordpress:9000;
            # all requests with php in it are sent through fastcgi to our wordpress container through port 9000
        }
        }
    }
}