user www.data;
# user under which nginx is running

worker_processes auto;
# indicates to nginx the number of processes the server must create to handle the client's request
# auto will adjust according to the number of CPU cores our server has

pid /run/nginx.pid;
# file where the PID (Process ID) is stored, this is the default one

events {}
# used to define parameters linked to the connexion (between server and host machine) and network
# events handled (http request received/sent, connexion established by client) by nginx
# we must keep it otherwise nginx will raise an error

http {
    include /etc/nginx/mime.types;
    # translates files names to their corresponding extension
    # used here because otherwise we have errors with CSS
    server {
        listen 443 ssl;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        root /var/www/wordpress;
        # files of the website
        server_name apeuget.42.fr;
        #the domain name

        index index.php
        # file(s) to look for when a request for an index is made
        # index is the default homepage file that web servers look for when someone visits a website

        location / {
            include snippets/fastcgi-php.conf;
            # to be able to use fastcgi I guess ?
            try_files $uri $uri/ =404;
        
        location ~ \.php$ {
            fastcgi_pass wordpress:9000;
            # all requests with php in it are sent through fastcgi to our wordpress container through port 9000
        }
        }
    }
}